### ISSUE TITLE
build constraints appear to be violated

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#10]
https://github.com/teaxyz/pantry.core/actions/runs/4180393129/jobs/7241331175

The command `tea +tea.xyz/brewkit build cairographics.org freetype.org gnome.org/glib=2.72.4 unicode.org gnome.org/gobject-introspection` tries to build `gnome.org/glib=2.75.3`.

**Comment by mxcl** [comment]
Works now apparently.
