### ISSUE TITLE
useGitHubAPI might be too completionist

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#102]
```sh
% time ./libexec/resolve.ts vim.org=9.0.1504
vim.org=9.0.1504
./libexec/resolve.ts vim.org=9.0.1504  0.53s user 0.13s system 0% cpu 1:18.21 total
```

78 seconds

https://github.com/teaxyz/pantry/actions/runs/4855206471/jobs/8654151355

Fails in GHA

https://github.com/vim/vim

16k tags

Perhaps we should pick a cap that will resolve in a reasonable amount of time? Since we're doing 100 tags per graphql query, this suggests vim is triggering 161 queries, or 2/s for 78s. Lets assume we only need the last 1000 (5s), maybe?

**Comment by mxcl** [comment]
the reason I did this was some projects have multiple release tracks, eg. 1.x, 2.x etc. and really there is no way to know if you are picking up all of anything without scanning all the tags.

eg. if vim hasn't published 1.x for 10 years, we need to find the tag even if it's 100 pages back. Not sure how else to do it.

Well I guess we can perhaps craft the graphQL query better?

**Comment by jhheider** [comment]
I doubt we can build vim 1 without a very different build system, but your point is taken. However, our current logic won't seem to resolve in github actions, so we do have a problem.

perhaps we can bypass our lookup if we are given a strict package requirement? that would solve unnecessarily grinding the graphql API when we're just trying to build a specific version (which is mostly).

**Comment by mxcl** [comment]
I think your patch is fine for now.

Basically it's not a solvable problem, with our current YAML. We could change the YAML specification system so you specify a regex for the github API instead. It's less UX but might be our best shot.

**Comment by jhheider** [comment]
As predicted and tested, it has fixed the build issues for `vim.org`: https://github.com/teaxyz/pantry/actions/runs/4885854664
