### ISSUE TITLE
Cannot download tar file for some github packages

### ISSUE THREAD

**Issue by ABevier** [pkgxdev/brewkit#113]
While attempting to package `gvisor-tap-vsock` I encountered the following:
```
pkg build
  
  building github.com/containers/gvisor-tap-vsock
  
  fetching /Users/alanbevier/tea/pantry/srcs/github.com∕containers∕gvisor-tap-vsock-0.6.1.tar.gz
mirror: 404: https://dist.tea.xyz/github.com/containers/gvisor-tap-vsock/v0.6.1.tar.gz
404: https://github.com/containers/gvisor-tap-vsock/archive/refs/tags/v0.6.1.tar.gz
tea expands the full semantic version, which may mean the URL you are
fetching is now incorrect. Try `version.raw`?
```
Using curl or copying and pasting the url into browser downloaded the file correctly.  This doesn't happen for all packages with code on github.  

I was able to work around this issue by setting GITHUB_ACTIONS=1 which fails over to using curl to download.

**Comment by mxcl** [comment]
This is deno being weird. I believe there was more error above with the original URL (and not our mirror) was is sourceforge per chance?

**Comment by jhheider** [comment]
`404: https://github.com/containers/gvisor-tap-vsock/archive/refs/tags/v0.6.1.tar.gz`

truly weird. was a complete `worksforme`, even across versions.
