### ISSUE TITLE
working-directory in build scripts doesn't like moustaches

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#117]
```yaml
    - run: |
        mv aws/* .
        rmdir aws
        ln -s . aws
      working-directory: "{{prefix}}/include"
```
produces:
```sh
mv aws/* .
rmdir aws
ln -s . aws
```
instead of:
```sh
OLDWD="$PWD"
mkdir -p "/Users/jacob/.tea/foo.bar/v1.2.3/include"
cd "/Users/jacob/.tea/foo.bar/v1.2.3/include"
mv aws/* .
rmdir aws
ln -s . aws
cd "$OLDWD"
unset OLDWD
```

**Comment by mxcl** [comment]
something suss there, even if it didn't tokenize (which it should, I'm looking at the code) the only way it wouldn't add the top and bottom boilerplate is if the yaml didn't have the right shape.

Got an example of it failing?

**Comment by jhheider** [comment]
That's the result of local testing. I was trying to use it when working out https://github.com/teaxyz/pantry/pull/1828

**Comment by jhheider** [comment]
I agree that it looks like it should work, from the code.
