### ISSUE TITLE
Make `actions/bottle` take target platform+arch

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#129]
Instead of `bottle` relying on the platform/arch of the runner it's on (not necessary, but of historical design), make it take the pair as an input so we can use freely-available ubuntu-latest runners for the bottle step, instead of queueing for our more limited custom runners.

**Comment by mxcl** [comment]
good plan

**Comment by jhheider** [comment]
Yeah. Was _hoping_ this was trivial, but of course, it uses the stowage and installed version. Which could be fine for most packages, but if we unpack `darwin+aarch64` tar into a tea prefix on `linux+x86-64`, we won't be able to bottle with it. So, we'd have to do it out of tree, which just means more changes.
