### ISSUE TITLE
Some bottles are too big to upload as a UInt8Array

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#130]
See the ~2GB linux+x86-64 bottles for `TTS`:

https://github.com/teaxyz/pantry/actions/runs/5248701941/jobs/9483951300

https://github.com/lucacasonato/deno_s3 looks like it hasn't had an update in 2 years. Migrate to using the `@awk_sdk`.

**Comment by jhheider** [comment]
closes https://github.com/teaxyz/pantry/issues/2167

**Comment by mxcl** [comment]
funzies. but yeah. no surprise that trying to shove 2GB into RAM is problematic

**Comment by jhheider** [comment]
I'm thinking the sanest solution might just to call the `s3` bin if the input is a `Path` and the size is over 1GB, since that punts on module issues and having to mess around with multi-part uploads.
