### ISSUE TITLE
Change location of docker mountpoint?

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/brewkit#140]
I decided to start over with my tea install and I decided to look at my old tea folder for interesting info, like to see why it was almost 29 GB large.

The folder that popped up to the top was tea.xyz/brewkit/mnt at 7GB. Maybe this can be moved somewhere else because I would never have thought that I needed to go in there to clean it up.

**Comment by jhheider** [comment]
What would you suggest? Keeping it under `brewkit` seems the most natural from a packaging perspective, and it "only" affects those building packages and running in linux.

I definitely think the mount points need better documentation, so others know where to find/clean stuff without reading `pkg-docker`, but documentation is every project's soft-spot (and can easily become stale as things evolve).

**Comment by magnusviri** [comment]
Maybe I should've waited before I posted the issue, because I kept looking through the tea stuff and the second large folder was tea.xyz/var/www, which looks like a cache of downloaded bottles. Edit: It's is 6 GB. That's 13 GB for basically 2 cache folders.

I think you guys should just create a cache folder that contains stuff that can be thrown away without affecting the behavior of tea. It would just force a redownload or rebuild of certain things.

**Comment by mxcl** [comment]
I was actually considering moving it to the pantry checkout recently under `prefixes/linux` or something

**Comment by mxcl** [comment]
> the second large folder was tea.xyz/var/www, which looks like a cache of downloaded bottles. Edit: It's is 6 GB. That's 13 GB for basically 2 cache folders.

yeah we really need to help prune that. @ABevier would like us not to cache at all which is maybe the right solution nowadays honestly

**Comment by magnusviri** [comment]
I'm fine with the caches, but they should be easy to clean out. And I think if hard drive space is low, then the old cache files should be removed, and if it's really low, it should just quit keeping the cache. You should make a variable that represents the minimum entry hard drive size, like 512 GB, or the actual hard drive, which ever is smaller, then multiply that by maybe .5 or .25 (so 256 or 128 GB) and make that the first clean up point. And then have a second mark, like .25 or .125 (128 GB or 64 GB) and then quit keeping the cache altogether.

As years go by and hard disks get bigger, just increase the 512 GB minimum entry hard drive size. So if the day ever comes that 2 TB is the minimum hard drive size, then you'd increase your cut offs. And of course, when this time comes, downloads will be similarly as giant, considering apps will probably just be giant AI models. And of course we'll have 1 Tbps fiber to homes. I'm sure. ;)

**Comment by mxcl** [comment]
Well that's fine and a set of great suggestions. But when do we do that? Every time `tea` runs? I don't think anyone would like it if running python was delayed while we pruned the cache. We could do it during installs but that also risks slowing that down. Most the time it should be nothing but sometimes it would be a lot.

Most pms don’t auto prune and have an explicit prune type command.

Our gui could auto prune though since it can do background tasks.

**Comment by magnusviri** [comment]
Yeah running it every time is wrong. What if the cli only cleans up when it installs and it only cleans up any old bottles of what it is installing. So it wont really clean things up, it just stops it from getting worse by replacing the old downloads with the new. 

And you could add a flag to the tea cli that performs cleanups manually.

**Comment by mxcl** [comment]
that sounds a pretty good idea
