### ISSUE TITLE
find: bin: No such file or directory

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/brewkit#147]
If i run `pkg` I get this error.

```
available commands:

find: bin: No such file or directory
```

I'm looking at the code for pkg and I don't see it cd, so it's running `find bin -type f | sed -ne 's/^pkg-/pkg /p'` in my pwd. I think my build environment is messed up. Maybe that's the problem?

**Comment by jhheider** [comment]
Definitely a bug: https://github.com/teaxyz/brewkit/blob/38df7b1e6ea3eb8c7643fdb7e3b75d929d4e42f0/bin/pkg#L5-L10

Easy fix though. Incoming.

**Comment by jhheider** [comment]
fixed in 0.39.1
