### ISSUE TITLE
Actionable error message for `no oauth token` error

### ISSUE THREAD

**Issue by abitrolly** [pkgxdev/brewkit#156]
The `no oauth token` error message is non-actionable.
```shell
$ ./tea pkg build postgresql.org@13.9
tea: installed: ~/.tea/cli.github.com/v2.32.1
no oauth token
```
Would be nice to get an instruction here about how to get the missing token with proper minimal permissions.

**Comment by jhheider** [comment]
do you have a `GITHUB_TOKEN` set? if you _don't_, here's what `pkg build` does:

https://github.com/teaxyz/brewkit/blob/8758df05de4bf8f57b36904fdd7a57d9b4f0ea1c/bin/pkg-build#L39-L42

you can run `./tea gh auth token` and see what it outputs. if that looks good, then `bash -x "$(./tea --prefix)"/tea.xyz/brewkit/v0/bin/pkg-build postgresql.org@13.9` should shed some more light on what's going on.

N.B.: please be careful not to expose your GitHub OAuth token here.

**Comment by abitrolly** [comment]
` ./tea gh auth token` is the command that is giving non-actionable output.

```
$ ./tea gh auth token
no oauth token
```

**Comment by jhheider** [comment]
great. looks like `gh` needs you to do `auth login` the first time.

**Comment by abitrolly** [comment]
@jhheider so how explain that in the error message?

**Comment by jhheider** [comment]
Likely trap the return for an error and replace that with a more informational message of our own.

Certainly it should be mentioned in the README.

**Comment by jhheider** [comment]
`gh` unable to authenticate. Have you run `tea gh auth login` before?

Maybe.

**Comment by mxcl** [comment]
yeah this sucks.

in full transparency we expect aspects of using brewkit to suck.

we did use to at least document you needed a github token or `gh` to be auth’d. Let me spend the time to improve this. I'd hate for people to get turned off.

**Comment by abitrolly** [comment]
I've got a feedback that default `gh auth login` permissions are `repo`, `read:org` and `gist`. And these have no expiry date.  https://github.com/cli/cli/discussions/7762

I am not sure these are not "too much" privileges, so maybe I will be able to bring up a more fine-grained instructions.

**Comment by abitrolly** [comment]
So one can create a token from the page https://github.com/settings/personal-access-tokens/new with up to 90 expire date (or custom date) and read only access to Public Repositories and set GITHUB_TOKEN to it.

**Comment by abitrolly** [comment]
I could start the postgresql@13.9 build with no permissions token, so it probably could be used as an instruction in error message.

![image](https://github.com/teaxyz/brewkit/assets/8781107/4d090501-9f1a-485c-8c16-e43688d805f5)

**Comment by mxcl** [comment]
Even builds need it unfortunately since we need the tag associated with the release.

However this could be cached and stored with the build.

Firmly agree our build infra is not as user friendly as I’d like. `brew` was better, but brew started off without bottles.
