### ISSUE TITLE
pkg command adds "\n" to the path on Ubuntu

### ISSUE THREAD

**Issue by and-ri** [pkgxdev/brewkit#167]
`$ pkg init test.test`
everything is fine, new/test.test branch and projects/test.test/package.yml are created

`$ pkg edit`
opens the \nprojects/test.test/package.yml file

`$ pkg build`
Uncaught Error: pkg not found: \ntest.test

`$ pkg test`
Uncaught Error: \ntest.test not installed in $TEA_PREFIX

brewkit version - v0.44.5

**Comment by jhheider** [comment]
I had hoped that https://github.com/teaxyz/brewkit/pull/163 would fix that.

Does this fix fix it? https://github.com/teaxyz/pantry/issues/326#issuecomment-1670025010

**Comment by and-ri** [comment]
> I had hoped that #163 would fix that.
> 
> Does this fix fix it? [teaxyz/pantry#326 (comment)](https://github.com/teaxyz/pantry/issues/326#issuecomment-1670025010)

It's works. Thank you!

![image](https://github.com/teaxyz/brewkit/assets/51118083/2e692666-0e06-4c0c-9d81-0857eb865ae9)
