### ISSUE TITLE
Add support for cloning source using git

### ISSUE THREAD

**Issue by ABevier** [pkgxdev/brewkit#17]
Currently Brewkit is only pulling tar'd archives from Github, however this results in a source structure where the .git folder is absent.  As some projects may use the git metadata during the build process it would be nice if there were the option to clone source from Github based on a tag.

**Comment by mxcl** [comment]
This was done

**Comment by felipecrs** [comment]
I'm trying to build [helmfile](https://github.com/teaxyz/pantry/issues/3458), and I'm trying to understand how can the brewkit clone using git.

Apparently there is no example in pantry, neither documentation for it.

Any pointers would be great :)

**Comment by felipecrs** [comment]
I think I found it now, don't worry: https://github.com/teaxyz/brewkit/blob/97fae5a4cff96e0c351e81e0e101f3c5767cb507/lib/usePantry.ts#L97

**Comment by mxcl** [comment]
sorry for the lack of docs. I will add it to my list. I want full docs for brewkit and pantry now we are 1.0

**Comment by felipecrs** [comment]
In fact I realized after that the sample package.yaml generated by `pkg init` contains some instructions, including this.

I'm actually happy with that.
