### ISSUE TITLE
nothing provides: init.ts

### ISSUE THREAD

**Issue by and-ri** [pkgxdev/brewkit#177]
```
and@and-ubuntu:~/Developer/pantry$ pkg init
× nothing provides: init.ts
│ we haven’t pkgd this yet. can you?
╰─➤ https://docs.pkgx.sh/pantry
```
```
and@and-ubuntu:~/Developer/pantry$ uname -a
Linux and-ubuntu 6.2.0-33-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by felipecrs** [comment]
Same issue here. Workaround was to:

```
$ pkgx install tea-pkg
$ tea-pkg init
```

**Comment by mxcl** [comment]
works for me. Probs revlock considering everything that happened. Ensure you have `pkgx 1.0` and shell integration then `dev`.

There are some issues with pantry/brewkit/pkgx at this time, but this works at least.

**Comment by mxcl** [comment]
oh ok, linux. I'll check that.

**Comment by mxcl** [comment]
Soz, this was only for the case where ruby wasn't installed, fixed in next point release which is coming up.

**Comment by jhheider** [comment]
macos: don't worry, you don't need to know what's on your system. don't think about it.
