### ISSUE TITLE
`constraint.single()` isn't preserving `version.raw`

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#202]
https://github.com/pkgxdev/brewkit/pull/196#issuecomment-1785964610

add `  console.info(pkg.version.raw)` to brewkit/libexec/resolve.ts at line 17:
```shell
% ./libexec/resolve.ts zlib.net   
zlib.net=1.3.0
1.3
```

add `console.info(version.raw)` to brewkit/libexec/query.ts at line 44:
```shell
% ./libexec/query.ts zlib.net=1.3.0 --src

1.3.0
```

this was wreaking havoc with pkgxdev/brewkit/pull/196 since it was testing generated distribution URLs (with HTTP HEAD requests), so calls to `getDistributable()` were failing. technically, they were always generating incorrect (but unused) URLs previously, and `fetch.ts` was using `usePantry().resolve()` which worked correctly. but this seems like a bug. right?

**Comment by mxcl** [comment]
well brewkit adding `.raw` is a hack to be fair. libpkgx doesn't support it. brewkit adds it to the object itself and it works because of coincidence.

edit: oh ok, no, raw is proper in this lib, I forgot and remembered something else.

**Comment by jhheider** [comment]
this was deep cut

**Comment by mxcl** [comment]
I need an example of it failing. This test passes:

```ts
assertEquals(new semver.Range("=1.0").single()!.raw, "1.0")
```

**Comment by mxcl** [comment]
k the bug is in getVersions. in brewkit.

**Comment by mxcl** [comment]
I'm not sure if this is a bug. The code gets the version from the source (eg github), the source dictates the raw version.

I need more details on why this is a bug in your opinion.

**Comment by isworking** [comment]
Take `catb.org/wumpus` and `zlib.net` as examples. The version it gets from the source is raw, which doesn't have `.0` (in minor) at end.  But when trying to fetch it, the `.0` is appended (probably the existing version object is stringified?). It's breaking the builds and tests for them, at least. Idk if it's a bug in BrewKit or something went wrong in my PR.

**Comment by jhheider** [comment]
> I need more details on why this is a bug in your opinion.

```shell
jacob@illithid brewkit % ./libexec/resolve.ts zlib.net
zlib.net=1.3.0
jacob@illithid brewkit % ./libexec/query.ts zlib.net=1.3.0 --url
brewkit: Could not fetch https://zlib.net/zlib-1.3.0.tar.gz [404]
null
```
using `usePantry().resolve()` properly populates `version.raw`. Using `pkg.constraint.single()` doesn't, resulting in the above bug.

**Comment by mxcl** [comment]
I think this is fixed with v1. Reopen if not. I traced code and couldn't see a place where `.raw` would be lost.
