### ISSUE TITLE
idea: run pkg build locally if dependencies exists locally but not in pantry

### ISSUE THREAD

**Issue by mfts** [pkgxdev/brewkit#25]
I am packaging `leptonica.org` and it has several dependencies that I have previously built and PR'd but are not yet merged and therefore not available in pantry. 

I have them in my `tea.out` locally tho and it would be great if `pkg build` system could use these if pantry cannot find them. 

```sh
 $ pkg build leptonica.org
error: Uncaught (in promise) Error: Not in pantry: github.com/uclouvain/openjpeg
```

```sh
$ ls tea.out/github.com
uclovain
```

**Comment by mxcl** [comment]
it won't work without the package.ymls too. Not sure how to handle that.

**Comment by mxcl** [comment]
if we copied the `package.yml` into tea-prefix after a successful build this would achieve that. It's a little dirty tho.

**Comment by mxcl** [comment]
oh well, this does work, while you are in your pantry checkout now ofc.

so strictly fixed. What isn't is if you want them to work when you leave the pantry. Need a new ticket for that.
