### ISSUE TITLE
`swift` doesn't like extended UTF-8 in `TMPDIR`

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#262]
Build issues in SwiftFormat and xcbeautify; fix below:

              ok, this fixes it:
```yaml
    - export TMPDIR=$(mktemp -d)
```
so, it's not liking, apparently, the extended unicode characters in the `TMPDIR` envvar. slightly gross. but an easy fix.

_Originally posted by @jhheider in https://github.com/pkgxdev/pantry/issues/4781#issuecomment-1885296990_

**Comment by mxcl** [comment]
I should probs should just drop the unicode characters in general.

**Comment by jhheider** [comment]
Colons. They're valid on normal filesystems, but rarely used in URLs (and why would we ever include one in a package name?).

**Comment by mxcl** [comment]
we don't add a colon deliberately. I didn't see an example of the failing TMPDIR in the attached link. Can you provide?

**Comment by jhheider** [comment]
you can get it locally easily enough (just comment out that one-line patch). here's an example in GHA: https://github.com/pkgxdev/pantry/actions/runs/7455318137/job/20284215852

**Comment by mxcl** [comment]
`TMPDIR=/Users/builder/actions-runner/_work/pantry/pantry/homes/tuist.io∕xcbeautify-1.4.0/tmp`

there’s no colon in that. I'm confused about the reference to colons I guess.

**Comment by jhheider** [comment]
sorry; was recommending regular old ASCII colons instead of fancy UTF-8 `∕`.

**Comment by mxcl** [comment]
oic. We should use a standard character. I may just switch to actual folders it's not that onerous.

**Comment by jhheider** [comment]
yeah, the only issue with folders is variable number of path elements, which the UTF-8 slash nicely bypasses. not impossible to work with, but something that's been mildly annoying in the past.

**Comment by mxcl** [comment]
I note that you have hardcoded `+brewing` in the pantry now. I was going to change the `+` to something that doesn't break regexes.

The examples that hardcode +brewing have no comments so I don't understand what is happening or why.

Please open tickets on brewkit, I cannot make brewkit more robust if all the fixes are one-off hacks in the pantry. Thank you.
