### ISSUE TITLE
`transform:`

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#270]
@mxcl: the `transform:` key seems like it might be behaving oddly. from the [build logs](https://github.com/pkgxdev/pantry/actions/runs/7506699325/job/20438689379?pr=4830) of https://github.com/pkgxdev/pantry/pull/4830:

```
{ v: "jdk-17.0.1+7", rv: "17.0.1.7" }
{ v: "jdk-17.0.1+8", rv: "17.0.1.8" }
{ v: "jdk-17.0.1+9", rv: "17.0.1.9" }
{ v: "jdk-17.0.1+10", rv: "17.0.1.10" }
{ v: "jdk-17-ga", rv: "17-ga" }
{ v: "jdk-17.0.1+11", rv: "17.0.1.11" }
{ v: "jdk-17.0.1+12", rv: "17.0.1.12" }
{ v: "jdk-17.0.2+1", rv: "17.0.2.1" }
{ v: "jdk-17.0.2+2", rv: "17.0.2.2" }
{ v: "jdk-17.0.1-ga", rv: "17.0.1-ga" }
{ v: "jdk-17.0.2+3", rv: "17.0.2.3" }
{ v: "jdk-17.0.2+4", rv: "17.0.2.4" }
{ v: "jdk-17.0.2+5", rv: "17.0.2.5" }
{ v: "jdk-17.0.2+6", rv: "17.0.2.6" }
{ v: "jdk-17.0.2+7", rv: "17.0.2.7" }
```
but it seems to be selecting the _first_ one `17.0.1.7` for `^17`, rather than `17.0.10.6`.

as an aside, should `strip:` and `transform:` be mutually exclusive? it looks like they're handled `transform` > `strip`, which surprised me, but there's no real reason it should have. as long as `version.tag` is still preserved, all should be fine. 🤞

**Comment by jhheider** [comment]
looks like the error is here: https://github.com/pkgxdev/brewkit/blob/769dd12d005834e8c30ab2ce2f256ebc1ba8519b/lib/hooks/usePantry.getVersions.ts#L308

that only seems returns the first line. trying some loop finagling to get the rest of the output.

**Comment by jhheider** [comment]
actually, it's much easier. just grab `cmd.output().stdout`.

**Comment by mxcl** [comment]
> as an aside, should strip: and transform: be mutually exclusive? it looks like they're handled transform > strip, which surprised me

I wasn't sure what order strip etc. should work in if coupled with transform. So elected to make them exclusive. I agree this is hidden knowledge and I hate that.

**Comment by jhheider** [comment]
i know vscode's editor knows which keys are valid for gha action schema. it'd be nice if there we could publish a schema for package.yml, though the flux is still high.
