### ISSUE TITLE
`pkg build` creates folder named w/ `/`: xyz.tea.build.sh is not found

### ISSUE THREAD

**Issue by getneil** [pkgxdev/brewkit#59]
<img width="777" alt="Screenshot 2023-03-29 at 9 47 37 PM" src="https://user-images.githubusercontent.com/7913978/228558747-61a93b46-2d1c-4436-9a44-f2c05580012d.png">

Generated folder:
<img width="461" alt="Screenshot 2023-03-29 at 9 39 56 PM" src="https://user-images.githubusercontent.com/7913978/228558800-eed784ee-788c-4792-8bd9-2cc11f04bc0d.png">

brewkit: 0.12.1

**Comment by mxcl** [comment]
fixed in 0.12.2

**Comment by mxcl** [comment]
https://github.com/teaxyz/pantry/actions/runs/4557879992
