### ISSUE TITLE
Uncaught (in promise) Error: 404: https://dist.tea.xyz/abseil.io/darwin/aarch64/versions.txt

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/brewkit#61]
This error makes no sense to me. My package.yml is far from done, so I'm not surprised I have an error. But afaik, there is no https://dist.tea.xyz/abseil.io, so I can't fathom why it's querying that url.

```
error: Uncaught (in promise) Error: 404: https://dist.tea.xyz/abseil.io/darwin/aarch64/versions.txt
    throw new TeaError('http', {cause})
          ^
    at get (https://raw.githubusercontent.com/teaxyz/cli/v0.25/src/hooks/useInventory.ts:37:11)
    at async select (https://raw.githubusercontent.com/teaxyz/cli/v0.25/src/hooks/useInventory.ts:16:20)
    at async file:///opt/tea/tea.xyz/brewkit/v0.11.4/libexec/install.ts:16:21
Caused by: Error: 404: https://dist.tea.xyz/abseil.io/darwin/aarch64/versions.txt
    at get (https://raw.githubusercontent.com/teaxyz/cli/v0.25/src/hooks/useInventory.ts:36:19)
    at async select (https://raw.githubusercontent.com/teaxyz/cli/v0.25/src/hooks/useInventory.ts:16:20)
    at async file:///opt/tea/tea.xyz/brewkit/v0.11.4/libexec/install.ts:16:21
```

**Comment by magnusviri** [comment]
The solution is to finish the package. I guess I'm documenting this because it's a very confusing error.

**Comment by jhheider** [comment]
The build step expects the completed package to be installed; usually I've seen this when the build script doesn't write anything under `{{ prefix }}`.

**Comment by mxcl** [comment]
We call `install.ts` for all deps for `test.ts` which is correct, `pkg test` is a separate command.

I'd argue the bug here is that the error thrown from `useInventory.ts` needs to get upgraded.

edit: Though that would lead to `no bottles available for foo.com` which may still be confusing here.

**Comment by magnusviri** [comment]
You could say, `no bottles available for foo.com. If you just built one, it produced nothing.`,

**Comment by mxcl** [comment]
we'd have to intercept here as the error originates in the tea/cli code where that would be confusing but yes could do.

**Comment by sanchitram1** [comment]
From https://github.com/teaxyz/pantry/pull/1276 -- there's no configure file, so I can't `./configure $ARGS`.  Is there a flag I can give when calling `make` to specify the prefix?

**Comment by jhheider** [comment]
no, the default target in https://github.com/ggerganov/whisper.cpp/blob/master/Makefile is `main`, which doesn't install anything, and there's no `install` target; you'll need to place the build products under `{{ prefix }}` yourself.
