### ISSUE TITLE
`fetch.ts` should display original download error if mirror returns a 404

### ISSUE THREAD

**Issue by leonsilicon** [pkgxdev/brewkit#67]
When developing a local package.yml, if the initial download fails, the current behaviour (https://github.com/teaxyz/brewkit/blob/main/libexec/fetch.ts#L63) is to swallow the original location error and fallback to the mirror (which always errors with a confusing 404 error for local-only packages):
```ts
    try {
      // first try the original location
      return await download({ dst, src: url })
    } catch {
      // then try our mirror
      const src = useOffLicense('s3').url(stowage)
      return await download({ dst, src })
    }
```

It would be better to throw the original error message if the mirror returns a 404 (meaning it was a local pantry package)

# Context

I was trying to build local pantry packages, but when I added a `GITHUB_TOKEN` environment variable, it broke `pkg build` with the following error:
```
  building stripe.com/stripe

  fetching /Users/leondreamed/.tea/tea.xyz/var/www/stripe.com∕stripe-1.13.12.tar.gz
downloading
downloading
404: https://dist.tea.xyz/stripe.com/stripe/v1.13.12.tar.gz
tea expands the full semantic version, which may mean the URL you are
fetching is now incorrect. Try `version.raw`?
```
To me, this error didn't make any sense (why would adding a `GITHUB_TOKEN` env variable cause it to fetch the package from `dist.tea.xyz`?), and I eventually traced it to the above section of code in `brewkit/libexec/fetch.ts`. Since the original `download` error is swallowed due to the mirror fallback, it's much harder for me to debug my issue of `GITHUB_TOKEN` causing the download to fail.

Update: turns out the issue was not checking the `public_repo` permission in my PAT

**Comment by mxcl** [comment]
yep agreed.

**Comment by mxcl** [comment]
v0.14 deploying. Once done `cd pantry && tea -SE && cd .` should switch the dev-env to the new release
