### ISSUE TITLE
pkg interactive build and test environments

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/brewkit#69]
I've been working on [micro](https://github.com/teaxyz/pantry/pull/466) and on Linux it gets a segfault. I've been debugging it. I had to reverse engineer how the docker build environment is setup. By doing this I was able to make some headway, but I'm not exactly sure what I figured out. It might be a different bug.

Anyway, can you make it easier to get an interactive terminal to the build and test environments?  Here's how I did it.

- I had to run `ps awwx` so I could get the docker command.
- I added "-it" to the docker command.
- I substituted `bash` instead of the tea command.
- I ran the new docker command
- I commented out the "set ..." commands that forced an exit on error in xyz.tea.build.sh and xyz.tea.test.sh.
- I ran the build and test scripts like this `. /pantry/builds/micro-editor.github.io-2.0.11+linux/xyz.tea.build.sh`

Doing this I was able to figure out that micro is actually working. So I'm not sure why the test is segfaulting. I think there's something in the test environment that is causing it to fail. I'm going to work on that next I think. If I figure it out I'll post another issue with the details.

Here's the docker command.

```
docker run -it --name tea --rm \
  --volume /opt/tea/tea.xyz/brewkit/mnt:/root \
  --volume /opt/tea/tea.xyz/var/www:/root/.tea/tea.xyz/var/www \
  --volume /root/.tea/tea.xyz/var/pantry \
  --volume /root/.tea/tea.xyz/var/pantries \
  --volume /opt/tea/tea.xyz/brewkit/v0.12.2:/opt/tea/tea.xyz/brewkit/v0.12.2 \
  --env GITHUB_TOKEN=ghp_secret \
  --env CLICOLOR_FORCE=1 \
  --volume /Users/james/pantry_mag:/pantry \
  --env TEA_PANTRY_PATH=/pantry \
  --env SRCROOT=/pantry teaxyz/cli bash
```

**Comment by mxcl** [comment]
yeah I'm sure we could add that. I'll noodle the syntax.

**Comment by mxcl** [comment]
we have been getting segfaults on linux for test in CI only
 a lot. It might be something to do with GitHub actions. That would suck.

**Comment by jhheider** [comment]
_Generally_ segfaults in CI are on ubuntu, due to it requiring PIE. We have some defaults to try and combat this (see: https://github.com/teaxyz/pantry/blob/e656a85b2deec68ecdefb3a2532870912761e402/projects/tea.xyz/gx/cc/package.yml#L16-L21), but that's not sufficient for every project. `Go` projects (like `micro`) need their own injection method.

**Comment by magnusviri** [comment]
Awesome! Thanks!
