### ISSUE TITLE
`usePantry().getVersions()` should support more providers

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#81]
Consider [Homebrew::Livecheck::Strategy](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy) for inspiration. Priorities should be:

- `curl.se/ca-certs`: needed for security
- `gnu: {{ pkg }}`: we have many of these
- `gitlab: {{ user/pkg }}`: GNOME and others like Gitlab

**Comment by mxcl** [comment]
The GNU one seems like it would  be just web scraping rather than GNU specific?

**Comment by jhheider** [comment]
Maybe. Gnu uses a very simple web-ftp layout. Not everyone is so friendly.

**Comment by mxcl** [comment]
k cool.
