### ISSUE TITLE
package.yml, versions, strip problem

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/brewkit#92]
[OpenJDK](https://github.com/openjdk/jdk20/tags) releases have components that need to be stripped from the beginning and end of the string. This is the download url.

https://github.com/openjdk/jdk{{ version.major }}u/archive/refs/tags/jdk-{{ version.raw }}-ga.tar.gz

AFAIK, regex doesn't allow you to match the start and end but ignore the middle. This could be solved by using a match w/ parenthesis, like this.

```
   strip: /^jdk-(.*)-ga/
```

**Comment by jhheider** [comment]
`strip` will take an array, I believe.

```yaml
strip:
  - /^jdk-/
  - /-ga$/
```

**Comment by mxcl** [comment]
yep it can take an array.

Also I already started an openJDK package.yml @magnusviri, before you get too far. It isn't finished though so feel free to finish it. There's an open PR for it.
