### ISSUE TITLE
idea: fixture support for the build: key

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#94]
Would be useful for package.ymls that require a small shim, like ruby gems.

**Comment by mxcl** [comment]
wouldn't be called a fixture in that situation tho. What you call it?

**Comment by jhheider** [comment]
Good question. Might just be `files:` for simplicity. Doesn't add much over files in the project directory except the ability to keep everything in yaml. It could be `build.files: { string: string }` to allow the option of just having any number of files inline. but it's mostly just a style change.

**Comment by mxcl** [comment]
`props` to stay in-line with where we copy extra files already

**Comment by mxcl** [comment]
I think: sure. But we should expand the fixture system so you can name them.

```yaml
fixture:
   name: foo.c
   content: |
```

and then it can take an array too

then call it props for the build

**Comment by jhheider** [comment]
Or possibly:

```yaml
fixtures:
  'foo.c': |
    // C code here
```

**Comment by mxcl** [comment]
oh yes, indeed! Much better idea.
