### ISSUE TITLE
gitlab specific versions

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/brewkit#95]
it's quite simple to do with the web scraper (see: [wumpus](https://github.com/teaxyz/pantry/blob/ac938bdcdba297045e7e7c4257321c60622df740/projects/catb.org/wumpus/package.yml#L5-L10), or [shared-mime-info](https://github.com/teaxyz/pantry/blob/ac938bdcdba297045e7e7c4257321c60622df740/projects/freedesktop.org/shared-mime-info/package.yml#L5-L10)). if we wanted to be able to wrap that complexity up for people, it'll likely look like this:
```yaml
versions:
  gitlab: [server/](user/repo|id)[/(releases|tags)]
```

it doesn't appear that we hit any obvious limits at either of the two API endpoints i used, and they're available on custom gitlab installs.

**Comment by mxcl** [comment]
would be sweet and make it clear we aren't github specific
